POST http://localhost:{{port}}/article/createArticle
Content-Type: application/json

{
  "title": "test",
  "tag": "testTag",
  "content": "asdfasdfasdfasdfasdfasdaf",
  "author": "fff"
}

###
POST http://localhost:{{port}}/user/modifyUser?name=fff
Content-Type: application/json

{
  "name": "fff",
  "age": 12
}

###
GET http://localhost:{{port}}/user/userInfo?name=aaa
Accept: application/json

###

POST http://localhost:{{port}}/login/loginWithCode
Content-Type: application/json

{
  "name": "fff",
  "password": "bbb",
  "code": "ccc"
}

###

###
GET http://localhost:{{port}}/login/getcode
Accept: application/json

###

