POST http://localhost:{{port}}/user/modifyUser?name=fff
Content-Type: application/json

{
  "name": "fff",
  "age": 12
}

###
GET http://localhost:{{port}}/user/userInfo?name=aaa
Accept: application/json

###
###
GET http://localhost:{{port}}/login/userInfo
Accept: application/json

###

POST http://localhost:{{port}}/login/loginWithCode
Content-Type: application/json

{
  "name": "aaa",
  "password": "bbb",
  "code": "ccc"
}

###

###
GET http://localhost:{{port}}/login/getcode
Accept: application/json

###

